---
title: "Following Gampopa"
---

## The Four Dharmas of Gampopa

#### **བདག་དང་སེམས་ཅན་ཐམས་ཅད་ཀྱི་བློ་ཆོས་སུ་འགྲོ་བར་བྱིན་གྱིས་བརླབ་:་གསོལ།**
`Dag thang sem chèn tham ché kyi lo chö su dro war jin gyi lab tu söl`<br>
Grant your blessing[^1] so that the mind of myself and all beings may be one with the dharma.

#### **ཆོས་ལམ་དུ་འགྲོ་བར༴**
`Chö lam du dro war jin gyi lab tu söl`<br>
Grant your blessing so that dharma may progress along the path.

#### **ལམ་འཁུལ་པ་སེལ་བར་བྱིན༴**
`Lam thrül pa sel war jin gyi lab tu söl`<br>
Grant your blessing so that the path may clarify confusion.

#### **འཁུལ་པ་ཡེ་ཤེས་སུ་འཆར་བར་བྱིན་གྱིས་བརླབ་:་གསོལ།**
`Thrül pa yè shé su tsjar war jin gyi lab tu söl`<br>
Grant your blessing so that confusion may dawn as wisdom.

[^1]: _jin gyi lab_ is usually translated as 'blessing', which may be misleading. The Tibetan term literally means to uplift and brighten. 'Grant your inspiration' may have better a better connotation. See [common misunderstandings about tantra](https://studybuddhism.com/en/tibetan-buddhism/tantra/buddhist-tantra/common-misunderstandings-about-tantra).


## Dedication

#### **བསོད་ནམས་འདི་ཡིས་ཐམས་ཅད་གཟིགས་པ་ཉིད། །**
`sö nam di yi tham chè siek pa nyi`<br>
By this merit, may we attain omniscience,

#### **ཐོབ་ནས་ཉེས་པའི་དགྲ་རྣམས་ཕམ་བྱས་ནས། །**
`thob ne nyè pay dra nam pham che ne`<br>
Defeat the enemy wrongdoing, and free

#### **སྐྱེ་རྒ་ན་འཆིའི་རྦ་རླབས་འཁུག་པ་ཡི། །**
`kyè ga na chii bar lap trüg pa yi`<br>
All wanderers from the ocean of existence

#### **སྲིད་པའི་མཚོ་ལས་འགྲོ་བ་སྒྲོལ་བར་ཤོག**
`si pay tso le dro wa dröl war shok`<br>
Churned by great waves of birth, age, sickness, and death.